# Generated by Django 4.0.4 on 2022-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.PositiveBigIntegerField(verbose_name='Ratings'),
        ),
    ]
